name: tability-clone
services:
  web:
    build:
      context: ..
      dockerfile: .neander/Dockerfile
    ports:
      - "8080:8080"
    secrets:
      - neander_environment
    x-google-cloudrun:
      ingress-container: true
secrets:
  neander_environment:
    file: /run/neander/secrets/neander_environment
x-neander:
  ingress:
    service: web
    port: 8080
    root_probe: /
  environment:
    - service: web
      name: DATABASE_URL
      required: true
      source: provisioned
      provider: Neon
    - service: web
      name: AUTH_SECRET
      required: true
      source: generated
      provider: null
      generator: opaque-random
  probes:
    - path: /
      success_status_range: 2xx
